services:
  # PostgreSQL Database with Vietnamese collation
  postgres:
    image: postgres:15
    container_name: smartrestaurant-postgres-dev
    environment:
      POSTGRES_DB: SmartRestaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - smartrestaurant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SmartRestaurant"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


  # ABP Backend API (Development)
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.api
      target: development
    container_name: smartrestaurant-api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Default=User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=SmartRestaurant;
    ports:
      - "44391:443"
      - "44390:80"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ../../aspnet-core:/app:delegated
    depends_on:
      - postgres
    networks:
      - smartrestaurant-network
    restart: unless-stopped

  # Angular Frontend (Development)
  web:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.web
      target: development
    container_name: smartrestaurant-web-dev
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"
    volumes:
      - ../../angular:/app:delegated
      - /app/node_modules
    depends_on:
      - api
    networks:
      - smartrestaurant-network
    restart: unless-stopped
    command: npm start

volumes:
  postgres_data_dev:
    driver: local

networks:
  smartrestaurant-network:
    driver: bridge