name: Security Scan

on:
  schedule:
    # Chạy vào 2:00 AM UTC mỗi ngày
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Cho phép chạy manual
  push:
    branches: [ main ]
    paths:
      # Chỉ chạy khi có thay đổi dependencies
      - '**/package*.json'
      - '**/packages.lock.json'
      - '**/*.csproj'
      - '**/Dockerfile*'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner (SARIF)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        exit-code: '0'
        
    - name: Run Trivy vulnerability scanner (Table for logs)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        exit-code: '0'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true
      
    - name: Install jq for JSON processing
      run: sudo apt-get update && sudo apt-get install -y jq
      
    - name: Show Trivy results summary
      if: always()
      run: |
        if [ -f "trivy-results.sarif" ]; then
          echo "🔍 Security Scan Results:"
          
          # Check if file has content
          if [ -s "trivy-results.sarif" ]; then
            # Count total vulnerabilities safely
            TOTAL_VULNS=$(jq '.runs[]?.results? // [] | length' trivy-results.sarif 2>/dev/null || echo "0")
            echo "Total vulnerabilities found: $TOTAL_VULNS"
            
            if [ "$TOTAL_VULNS" -gt "0" ]; then
              echo "❌ Security vulnerabilities detected. Check the Security tab for details."
              
              # Show vulnerability details
              jq -r '.runs[]?.results[]? | "\(.ruleId // "Unknown"): \(.message.text // "No message")"' trivy-results.sarif 2>/dev/null || echo "Could not parse vulnerability details"
              
              exit 1
            else
              echo "✅ No security vulnerabilities found."
            fi
          else
            echo "⚠️ Scan results file is empty"
          fi
        else
          echo "⚠️ No scan results found"
        fi

  # .NET specific security scan
  dotnet-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore .NET dependencies
      run: |
        cd aspnet-core
        dotnet restore SmartRestaurant.sln

    - name: Run .NET security audit
      run: |
        cd aspnet-core
        dotnet list package --vulnerable --include-transitive || true

  # Node.js specific security scan
  npm-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd angular
        npm ci

    - name: Run npm audit
      run: |
        cd angular
        npm audit --audit-level high || true

    - name: Check for known vulnerabilities
      run: |
        cd angular
        npx audit-ci --config audit-ci.json || true